version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8080:8080"
    privileged: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    ports:
      - "3000:80"
